module.exports = {
  // socket event
  SUBSCRIBE_PAGE_CHANGES_EVENT: 'SUBSCRIBE_PAGE_CHANGES_EVENT',
  PAGE_CHANGES_EVENT: 'PAGE_CHANGES_EVENT',

  ACTIVE_PAGE_EVENT: 'ACTIVE_PAGE_EVENT',
  ACTIVE_PAGE_SUCCESSFUL_EVENT: 'ACTIVE_PAGE_SUCCESSFUL_EVENT',
  ACTIVE_PAGE_FAILURE_EVENT: 'ACTIVE_PAGE_FAILURE_EVENT',
  ACTIVE_PAGE_UPDATE_EVENT: 'ACTIVE_PAGE_UPDATE_EVENT',

  ALERT_TIME_DISMIS: 2500,
  MAX_TAG_ITEMS: 6
};
