export const SUBSCRIBE_PAGE_CHANGES_EVENT = 'SUBSCRIBE_PAGE_CHANGES_EVENT';
export const PAGE_CHANGES_EVENT = 'PAGE_CHANGES_EVENT';
export const ACTIVE_PAGE_EVENT = 'ACTIVE_PAGE_EVENT';
export const ACTIVE_PAGE_SUCCESSFUL_EVENT = 'ACTIVE_PAGE_SUCCESSFUL_EVENT';
export const ACTIVE_PAGE_FAILURE_EVENT = 'ACTIVE_PAGE_FAILURE_EVENT';
export const ACTIVE_PAGE_UPDATE_EVENT = 'ACTIVE_PAGE_UPDATE_EVENT';
