export const SUBSCRIBE_PAGE_CHANGES_EVENT = 'SUBSCRIBE_PAGE_CHANGES_EVENT';

export const PAGE_CHANGES_EVENT = 'PAGE_CHANGES_EVENT';

export const ACTIVE_PAGE_EVENT = 'ACTIVE_PAGE_EVENT';
export const ACTIVE_PAGE_SUCCESSFUL_EVENT = 'ACTIVE_PAGE_SUCCESSFUL_EVENT';
export const ACTIVE_PAGE_FAILURE_EVENT = 'ACTIVE_PAGE_FAILURE_EVENT';
export const ACTIVE_PAGE_UPDATE_EVENT = 'ACTIVE_PAGE_UPDATE_EVENT';

export const SUBSCRIBE_PROJECTS_CHANGES_EVENT = 'SUBSCRIBE_PROJECTS_CHANGES_EVENT';
export const UN_SUBSCRIBE_PROJECTS_CHANGES_EVENT = 'UN_SUBSCRIBE_PROJECTS_CHANGES_EVENT';

export const PROJECTS_CHANGES_EVENT = 'PROJECTS_CHANGES_EVENT';

export const SUBSCRIBE_PAGES_CHANGES_EVENT = "SUBSCRIBE_PAGES_CHANGES_EVENT";
export const UN_SUBSCRIBE_PAGES_CHANGES_EVENT = "UN_SUBSCRIBE_PAGES_CHANGES_EVENT";
export const GET_HISTORY_PAGE_EVENT = "GET_HISTORY_PAGE_EVENT";
export const GET_HISTORY_PAGE_SUCCESSFUL_EVENT = "GET_HISTORY_PAGE_SUCCESSFUL_EVENT";
export const GET_HISTORY_PAGE_FAILURE_EVENT = "GET_HISTORY_PAGE_FAILURE_EVENT";
